apiVersion: v2
name: victoriametrics-authentik-gateway
description: Authentik outpost, VMAuth proxy and Gateway HTTPRoute for Victoria Metrics SSO authentication
type: application
version: "0.0.3"
appVersion: "1.0.0"
keywords:
  - monitoring
  - victoriametrics
  - authentik
  - sso
  - vmauth
  - gateway
  - outpost
  - observability
dependencies:
  - name: victoria-metrics-auth
    version: "0.20.0"
    repository: https://victoriametrics.github.io/helm-charts/
    alias: vmauth
    condition: vmauth.enabled
