{{- if .Values.vlsingle.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.namePrefix }}-vlsingle
  namespace: argocd
  labels:
    {{- include "argocd-victoriametrics-stack.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.vlsingle.syncWave | quote }}
  finalizers:
    - argoproj.io/resources-finalizer
spec:
  project: {{ .Values.project }}
  source:
    repoURL: {{ .Values.vlsingle.chart.repoURL }}
    targetRevision: {{ .Values.vlsingle.chart.version }}
    chart: .
    helm:
      {{- if or .Values.vlsingle.chart.nameOverride .Values.vlsingle.values }}
      values: |
        {{- if .Values.vlsingle.chart.nameOverride }}
        nameOverride: {{ .Values.vlsingle.chart.nameOverride }}
        {{- end }}
        {{- with .Values.vlsingle.values }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
  destination:
    name: {{ .Values.destinationCluster }}
    namespace: {{ .Values.namespaces.stack }}
  syncPolicy:
    {{- toYaml .Values.syncPolicy | nindent 4 }}
{{- end }}
