apiVersion: v2
name: victoriametrics-vlsingle
description: VLSingle CRD for Victoria Logs single instance deployment
type: application
version: "0.0.3"
appVersion: "1.0.0"
keywords:
  - monitoring
  - victorialogs
  - vlsingle
  - logs
  - observability
