apiVersion: v2
name: victoriametrics-vmauth
description: VMAuth CRD for Victoria Metrics authentication proxy
type: application
version: "0.0.1"
appVersion: "1.0.0"
keywords:
  - monitoring
  - victoriametrics
  - vmauth
  - authentication
  - proxy
  - observability
