{{- if .Values.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  retentionPeriod: {{ .Values.retentionPeriod | quote }}
  replicaCount: {{ .Values.replicaCount }}
  storage:
    accessModes:
      {{- toYaml .Values.storage.accessModes | nindent 6 }}
    {{- if .Values.storage.storageClassName }}
    storageClassName: {{ .Values.storage.storageClassName }}
    {{- end }}
    resources:
      requests:
        storage: {{ .Values.storage.size }}
  resources:
    {{- if .Values.resources.requests }}
    requests:
      {{- toYaml .Values.resources.requests | nindent 6 }}
    {{- end }}
    {{- if .Values.resources.limits }}
    limits:
      {{- toYaml .Values.resources.limits | nindent 6 }}
    {{- end }}
  {{- if .Values.extraArgs }}
  extraArgs:
    {{- range $key, $value := .Values.extraArgs }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- end }}
