apiVersion: v2
name: victoriametrics-vmsingle
description: VMSingle CRD for Victoria Metrics single instance deployment
type: application
version: "0.0.4"
appVersion: "1.0.0"
keywords:
  - monitoring
  - victoriametrics
  - vmsingle
  - metrics
  - observability

